In [23]:
import pandas as pd
import numpy as np
import lightgbm as lgb
import pathlib
from sklearn.model_selection import train_test_split
import pickle

ROOT_PATH = pathlib.Path().resolve().parents[0]

In [18]:
X_df = pd.read_csv(ROOT_PATH/"csv/2023-07-03X_df.csv")
y_df = pd.read_csv(ROOT_PATH/"csv/2023-07-03y_df.csv")["ncld"]

In [19]:
X_df["time"] = pd.to_datetime(X_df["time"])
X_df = X_df.drop(["time","lat","lon"],axis=1)

In [25]:
X_df

,psea,sp,u,v,temp,rh,r1h,dswrf
0,100777.064114,100564.219806,4.483181,-1.828746,266.750890,55.862386,200.000000,665.0000
1,100679.816409,100466.054670,5.981652,2.648318,267.025307,91.713302,0.740055,121.1350
2,100576.146687,100360.550085,1.113150,-14.477065,270.252969,60.800459,1.272165,102.2340
3,100761.009068,100545.871182,-0.036697,-13.749236,269.241548,62.678900,200.000000,665.0000
4,100885.320993,100665.137235,-2.048930,-12.079511,268.828616,64.220184,-0.000007,334.1710
...,...,...,...,...,...,...,...,...
1988515,101737.155839,101533.027127,-5.284404,-3.308869,296.628324,79.277523,0.048923,0.0005
1988516,101738.531986,101543.118870,-5.235474,-3.027523,296.447993,81.158257,0.134550,0.0005
1988517,101716.054922,101513.761073,-4.629970,-2.061162,295.907000,85.155963,200.000000,665.0000
1988518,101771.100793,101574.311530,-4.605505,-2.293578,296.251981,84.442660,0.948006,0.0005
1988519,101783.027398,101588.072998,-4.605505,-2.844037,296.270276,85.355504,0.287455,10.8655

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.3)
lgb_train = lgb.Dataset(X_train,y_train)

In [21]:
params = {
    'objective': 'regression',
    'metric': 'mse'
}

In [22]:
model = lgb.train(params, lgb_train)

[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005568 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2040
[LightGBM] [Info] Number of data points in the train set: 1391964, number of used features: 8
[LightGBM] [Info] Start training from score 42.563421

In [24]:
filename = "models/model_using_msm_extract_only_amedas_point.pkl"
with open(ROOT_PATH/filename,"wb") as f:
    pickle.dump(model,f)